### ISSUE TITLE
Usage with dune

### ISSUE THREAD

**Issue by dboris** [darioteixeira/pgocaml#103]
I have set the environment variables as per the usage instructions:
```sh
% printenv | grep PG
PGUSER=pgtest
PGPASSWORD=pgtest
PGHOST=localhost
PGDATABASE=pgtest
```

When I try to build a test project with dune, I get:
```
% dune build bin/main.exe
File "bin/main.ml", line 4, characters 6-11:
4 |     [%pgsql dbh "insert into employees (name, salary) VALUES ($name, $salary)"]
          ^^^^^
Error: PG'OCaml PPX error: Could not make the connection host=unix,
       port=5432, user=boris, password=*****, database=boris, error:
       PGOCaml_generic.Make(Thread).Error("PGOCaml: Could not connect to
       database")
```

The environment variables don't seem to be visible for dune. Is there some sandboxing going on, or is there some other dune-specific setup that is required?

**Comment by vouillon** [comment]
That should work. Maybe `dune` has cached a previous failure? Try `dune clean`.

**Comment by dboris** [comment]
@vouillon Thanks, works after `dune clean`.
