### ISSUE TITLE
Switch pcre to ocaml-re?

### ISSUE THREAD

**Issue by rgrinberg** [darioteixeira/pgocaml#15]
I prefer PGOcaml over ocaml-postgres partially because pgocaml doesn't have any extraneous non OCaml dependencies. PGOCaml has a little blemish in this sense that it relies on pcre. I've glanced over the usage of pcre and it seems like it could easily be replaced with ocaml-re.

I can make this effort myself if you think this is an acceptable change.

**Comment by darioteixeira** [comment]
It is definitely acceptable!  In fact, I'm already migrating all my projects from PCRE to OCaml-re, and I will get to PG'OCaml eventually.  If, however, you wish to submit a PR, that would be most welcome.  It's okay to use the `re.pcre` module, which makes the transition (amost) painless.

One note: the current OCaml-re master has some incompatible API changes with release 1.4.1.  Do you know if a release is imminent?

**Comment by rgrinberg** [comment]
> One note: the current OCaml-re master has some incompatible API changes with release 1.4.1. Do you know if a release is imminent?

Which changes in particular? I don't see any breaking changes so far. I don't see any here:

https://github.com/ocaml/ocaml-re/compare/ocaml-re-1.4.1...master

Maybe I'm blind though.

If you'd like to see a release I can start preparing one (update CHANGES, etc.)

**Comment by darioteixeira** [comment]
I was referring to the addition of the `Group` submodule.  However, I just noticed that the old functions are still part of the API, just marked as deprecated.  Never mind...

**Comment by rgrinberg** [comment]
@darioteixeira Would be great to have a new release of pgocaml. Since pcre is only required for the syntax extension now.

**Comment by darioteixeira** [comment]
@rgrinberg Yeap.  Though I'd rather have the whole library using `re`.  I might find some time this weekend to convert the syntax extension.

**Comment by darioteixeira** [comment]
I have now converted the syntax extension from OCaml-pcre to OCaml-re.
I'll send a message to the PG'OCaml mailing-list, so users can test the new version before release.

**Comment by rgrinberg** [comment]
@darioteixeira Do you think it's a good time to make the release now?

**Comment by darioteixeira** [comment]
@rgrinberg: Sure. I'll do it this weekend.

**Comment by darioteixeira** [comment]
@rgrinberg: I'm delaying the release for a few more days, as we just had a new PR and there may more in the pipeline (I've sent an email to the `pgocaml-general` list).

**Comment by darioteixeira** [comment]
I've just tagged 2.3.  OPAM package is on the way...
