### ISSUE TITLE
Cannot reference a variable with $ inside jsonb type

### ISSUE THREAD

**Issue by RuyBlast** [darioteixeira/pgocaml#93]
Hi !
Following ppx code does not work:
``` [%pgsql dbh "UPDATE users SET info = (info || '{$key : $value }'::jsonb)"] ```
because it references a $ inside a type json, as spots following error message:
```
Error: PG'OCaml PPX error: Postgres backend error:
ERROR: 22P02: invalid input syntax for type json:
ERROR: 22P02: invalid input syntax for type json(S: ERROR),(V: ERROR),(C: 22P02),
(M: invalid input syntax for type json),(D: Token "$" is invalid.),(W: JSON data, line 1: {$...),
(P: 48),(F: json.c),(L: 1248),(R: report_invalid_token)
```
It seems to me like a bug, but maybe I am approaching the problem the wrong way. What do you think of it ?

(I tried several workarounds that did not work like
``` [%pgsql dbh "UPDATE users SET info = (info || '{\"$key\" : \"$value\" }'::jsonb)"] ```)

Thanks a lot for reading and your great work !

**Comment by vouillon** [comment]
You cannot put a variable inside an SQL string. This should work:
```
[%pgsql dbh "UPDATE users SET info = (info || jsonb_build_object($key :: text, $value :: text))"]
```

**Comment by RuyBlast** [comment]
Indeed it works perfectly! Thanks a lot :)
